### ISSUE TITLE
Ranks not working getting: "This feature is disabled on the server!"

### ISSUE THREAD

**Issue by AngelShadow9451** [FTBTeam/FTB-Utilities#1002]
I am oped on the server and none of the ranks are loading up and it keeps saying "This feature is disabled on this server!" I feel like this should be an easy fix but I have been at it for the last 6 hours :/ 

ftbutilities.cfg:
![image](https://user-images.githubusercontent.com/47091486/58509374-0b6a4900-815c-11e9-9520-eaf90d465728.png)
![image](https://user-images.githubusercontent.com/47091486/58509420-21780980-815c-11e9-9af1-f2c9182b572b.png)

Ranks.txt file located in /local/ftbutilities/ranks.txt
![image](https://user-images.githubusercontent.com/47091486/58509225-a6aeee80-815b-11e9-9118-3a4ee584645c.png)

**Comment by ktole1999** [comment]
and these are the settings on the server or your client?

**Comment by AngelShadow9451** [comment]
These are the Settings on the Server

**Comment by ktole1999** [comment]
any other mods you are using for permissions?

**Comment by AngelShadow9451** [comment]
Thut Perms

**Comment by AngelShadow9451** [comment]
omg I figured it out it was Thut perms, after removing it the ranks worked fine.
