### ISSUE TITLE
Claims are not working properly

### ISSUE THREAD

**Issue by Sognus** [FTBTeam/FTB-Utilities#1019]
Hello,
either it is a bug or I am just unable to make following work. No matter what I do players are still able to access claims they do not own or they are not part of team that claimed those chunks. I have already tried to change permissions a bit but it does not seems to have any kind of positive result. 

I am not really sure if it is my mistake or not because every documentation I have found seemed to be really outdated, wiki was moved but it seems to be empty for me.

If it proves to be a bug I can provide more info if neccesary. 

**Possible helpfull info:** 
FTBU Version: 5.4.0.99
Java version: 1.8.0_212
OS: Debian 10 (don't ask me how I managed to install java 8 there)
Modpack: Omnifactory (V1.2.1)

**Comment by Sognus** [comment]
Players are able to open inventories (i.e chests, hoppers and their modded variants. They are able to open doors, break blocks, etc. It's as if FTBu is not working at all.

**Comment by TerdyTheTerd** [comment]
I would assume you have been over the config file, specifically the world section.

**Comment by ItsMeZioh** [comment]
I am also having this problem, I claimed an entire island, have no one allied, team setting is set to members only. anyone can access storage, open chest ETC, even testing in SP with only the mod and lib loaded, no luck
