### ISSUE TITLE
command.ftbutilities.nick Permission is set, still getting a dont have permission error

### ISSUE THREAD

**Issue by Lynexia** [FTBTeam/FTB-Utilities#1029]
I don't know how it's supposed to be formatted but I have tried a couple different variations.

Ranks.txt

[player is default_player_rank]
command.ftbutilities.nick
example.permission: true
example.other_permission: false
ftbutilities.homes.max: 1
ftbutilities.homes.cooldown: 3600000
ftbutilities.homes.warmup: 15000
ftbutilities.nickname.colors: false
ftbutilities.nickname.set: true
ftbutilities.chunkloader.max_chunks: 1
ftbutilities.claims.max_chunks: 20

[admin is default_op_rank]
example.other_permission: true

**Comment by tony84727** [comment]
It should be `ftbutilities.chat.nickname.set`.
You can reference all permission nodes in generated HTML(named `all_permissions.html`), which I believe is in the `local/ftbutilities` folder
![image](https://user-images.githubusercontent.com/45312147/64716680-60f11880-d4f5-11e9-9760-65d278a00eea.png)

**Comment by spiral6** [comment]
I don't have said generated HTML in my folder. How do I get it to generate/show up?
