### ISSUE TITLE
[Bugs] Render Tooltips

### ISSUE THREAD

**Issue by Rumaruka** [FTBTeam/FTB-Utilities#1031]
Versions:
Minecraft - 1.12.2
Forge - 14.23.5.2838
FTBLibs - 5.4.3.132
FTBUtilites - 5.4.0.102
Little bugs, but uncomfortable
![image](https://user-images.githubusercontent.com/8148679/63706823-ced8e700-c849-11e9-997e-654d833a7fcb.png)

**Comment by Rumaruka** [comment]
> #1010
> FTBLib is what actually handles the rendering of the tooltips. I had attempted to fix this be changing various z-levels for the different rendering GUI's, but was unable to pinpoint the exact class/method and values needed in my limited time of testing it.

Tell me, if you can fix this =)

**Comment by TerdyTheTerd** [comment]
My other idea was to simply change the location to be on the left side, since nothing usually renders there (the item zoom mod does). Ill re-visit it and see if I can locate it, perhaps make the side a config thing
