### ISSUE TITLE
Can't actually build the 1.7 branch.

### ISSUE THREAD

**Issue by draknyte1** [FTBTeam/FTB-Utilities#1063]
Hey there, I was looking to get FTBU working in dev. 

From what I can see though, 1.7 has a non-functioning build script/setup. (Both FTBU & FTBLib) While I did replace the existing scripts with some that work, there's a few problems.

Attempting to clone and compile the 1.7 branch of FTBU against FTBLib-1.7.10-1.0.18.3-dev fails.
Attempting to clone and compile the 1.7 branch of FTBLib also fails, as it relies on LatCore.
Attempting to clone LatCore is fine, compiles correctly after replacing the sun.unsafe nullable import. However, it's package structure differs from what the cloned FTBLib requires, or at times, is missing classes entirely.

Before I sink in the time to figure this out myself at 3am, I figure I'd ask...

Thanks,
Alkalus

**Comment by Ihysoal** [comment]
Gonna just casually bump this issue because it is an issue that I'm having issues with.
