### ISSUE TITLE
Chunk Loading issue

### ISSUE THREAD

**Issue by mangogamr** [FTBTeam/FTB-Utilities#1081]
I'm in a server for project ozone 3 kappa mode.version 3.2.51 And a lot of the time when I change dims and crash (my laptop is a big potato) and sometimes when I don't crash. The chunkloading stops working and I can't use my storage tablet conect to my storage scanner

Long story short. The chunk loading bugs out a lot for me on po3 when I change dims

edit: had a player tp to me while im in the mining dim, my chunk loading not working. and go to my base i have access to my storage system
and then have them coem back, it works for a few moments after that, and then it stops wotking again

loading the chunks didnt jumpstart my ftb loading

edit2: unclaimed everything, and left the team, made a new one, and claimed adn chunkloaded my base again, doesnt work, not the team bugged, its me, not the team

 also tried to claim and chunk load where i am in another dim, still didnt jump start my base chunks

**Comment by Ludi87** [comment]
FTB Chunk loading is disabled in PO3. Use something else
