### ISSUE TITLE
Data (homes, claims, loaded chunks) not saving

### ISSUE THREAD

**Issue by Teibidh** [FTBTeam/FTB-Utilities#1090]
My server and modpack were working wonderfully and I was quite happy with FTB Utilities but as of last night my homes, claims and loaded chunks are no longer being saved across server restarts. I did not add any mods that were not there before. There are no errors that I see in logs that look related so I'm really not sure what to do troubleshoot this issue myself but am willing to try suggestions.

Minecraft: 1.12.2
Forge: 14.23.5.2487
FTBLib: 5.4.6.0
FTB Utilities: 5.4.0.124

+ See if the issue isn't already reported / suggestion been made by looking up some keywords.
 * Searched for "claims not saving" and "homes not saving" did not find issues, nor did I find anything that looked related on the recent open issues.

+ If it is, don't comment that you have the same issue, just press :+1:

+ Bugs and Suggestions will only be accepted and implemented/fixed for latest minecraft version, unless it's compatible with older one.
 Minecraft: 1.12.2 -- But this issue just started.

+ Do not add versions or "[Bug]" or "[Suggestion]" in issue title, I will tag them.

**Comment by LatvianModder** [comment]
Has been fixed in FTB Library 5.4.7.0
