### ISSUE TITLE
Errors being thrown between FTB Utilities and Journeymap when rendering a claimed area on map.

### ISSUE THREAD

**Issue by knoxhack** [FTBTeam/FTB-Utilities#1091]
https://github.com/NFINIT-Development/Astroblock2/issues/1

Crashlog: 
https://github.com/NFINIT-Development/Astroblock2/files/4270569/crash-2020-02-29_16.22.05-client.txt

**Comment by Norway174** [comment]
Can confirm this happens to on my ModPack: https://github.com/Norway174/Peanut-Craft

I don't know if this is because of JoruneyMap or because FTB Utilities. But figured I'd toss in my own crashlog, since the issue was already here.

Crashlog: https://paste.dimdev.org/horovodesu.mccrash

**Comment by Globyr** [comment]
Was playing with ModPack and when opened FTB to claim chunks, had an errors. After some time of playing game started to lag with same error every time, when it was lagging. 

Crashlog: 
[crash-2020-04-27_14.54.54-client.txt](https://github.com/FTBTeam/FTB-Utilities/files/4539457/crash-2020-04-27_14.54.54-client.txt)
