### ISSUE TITLE
Claimed Chunks With Ice and Fire

### ISSUE THREAD

**Issue by bloo1147** [FTBTeam/FTB-Utilities#1104]
A few friends and I just started a new 1.12.2 server with the Ice and Fire mod installed.  We were under the impression that claimed chunks are protected.  However, dragons still destroy blocks inside of claimed chunks.  Is this intended?  We are going to disable dragon griefing until we know for sure.

**Comment by TheMightyMcGrew** [comment]
Yeah this is a huge issue, as a modded server owner Im terrified to allow dragon griefing. Which ruins part of the immersion of our modpack because it makes fighting the dragons in the wild super stupid easy. An update on this would be nice, or even a hint of acknowledgement you know?
