### ISSUE TITLE
Teams not working on server, possibly ranks too

### ISSUE THREAD

**Issue by Kynrasian** [FTBTeam/FTB-Utilities#1109]
On a 1.12.2 FTB Revelation server I'm helping run, some players can't create teams (the GUI kicks them out and says they don't have permission), no-one can invite others to their team, and our ranks setup to manage how many chunks players can claim/load isn't currently functioning either.

Here's the ranks file:
[ranks.txt](https://github.com/FTBTeam/FTB-Utilities/files/4637389/ranks.txt)

**Comment by Tahakk** [comment]
Are you sure that those players getting rank?

just a side note:
you could do parenting and thus only write changes between ranks :)

**Comment by Kynrasian** [comment]
If they're not, /ranks get is definitely still telling me they are.

And yeah, I realised that later, but decided I'd fix the formatting once I'd fixed the fact that it's not even working at the moment >_>

**Comment by Kynrasian** [comment]
*sigh* Don't know how I missed this the first time I went looking. This fixes the issue.
https://github.com/FTBTeam/FTB-Utilities/issues/992
