### ISSUE TITLE
My customs ranks 

### ISSUE THREAD

**Issue by FullGreenDev** [FTBTeam/FTB-Utilities#1137]
Hello 

My customs ranks didn't show in the game

Code : 

[player]
power: 1
default_player_rank: true
ftbutilities.claims.block.edit.gravestone.gravestone: true
command.ftbutilties.home: false // Deny players from using homes
ftbutilities.claims.max_chunks: 20 
ftbutilities.chunkloader.max_chunks: 5
ftbutilities.claims.block.edit.gravestone.gravestone: true
ftbutilities.chat.name_format: &aJoueur &0&1>> &l{name}&r >> 

[player+]
power: 1
default_player_rank: true
ftbutilities.claims.block.edit.gravestone.gravestone: true
command.ftbutilties.home: false // Deny players from using homes
ftbutilities.claims.max_chunks: 25 
ftbutilities.chunkloader.max_chunks: 5
ftbutilities.claims.block.edit.gravestone.gravestone: true
ftbutilities.chat.name_format: &aJoueur+ &0&1>> &l{name}&r &1&0>>&r

[vip]
power: 10
ftbutilities.claims.max_chunks: 30
ftbutilities.claims.block.edit.gravestone.gravestone: true
ftbutilities.chunkloader.max_chunks: 15
ftbutilities.chat.name_format: &2VIP &0&1>> &l{name}&r &1&0>>&r
command.ftbutilities.feed: true
ftbutilities.back.infinite

[vip+]
power: 10
ftbutilities.claims.max_chunks: 50 
ftbutilities.chunkloader.max_chunks: 30
ftbutilities.chat.name_format: &5VIP+ &0&1>> &l{name}&r &1&0>>&r
command.ftbutilities.feed: true
command.ftbutilities.heal: true
ftbutilities.back.infinite

[admin] 
power: 1000
default_op_rank: true
command: true 
ftbutilities.claims.block.edit.gravestone.gravestone: true
ftbutilities.chat.name_format: &4Admin &1>> &f{name}&r &0>>&r

THX for your help

**Comment by PotFlux** [comment]
Not sure if you got it figured out or not but I tried to fix your ranks.

[player]
power: 1
default_player_rank: true
ftbutilities.claims.block.edit.gravestone.gravestone: true
command.ftbutilties.home: false // Deny players from using homes
ftbutilities.claims.max_chunks: 20
ftbutilities.chunkloader.max_chunks: 5
ftbutilities.claims.block.edit.gravestone.gravestone: true
ftbutilities.chat.name_format: &aJoueur &0&1>> &l{name}&r >>

[player+]
power: 10
parent: player
ftbutilities.claims.block.edit.gravestone.gravestone: true
command.ftbutilties.home: false // Deny players from using homes
ftbutilities.claims.max_chunks: 25
ftbutilities.chunkloader.max_chunks: 5
ftbutilities.claims.block.edit.gravestone.gravestone: true
ftbutilities.chat.name_format: &aJoueur+ &0&1>> &l{name}&r &1&0>>&r

[vip]
power: 20
parent: player+
ftbutilities.claims.max_chunks: 30
ftbutilities.claims.block.edit.gravestone.gravestone: true
ftbutilities.chunkloader.max_chunks: 15
ftbutilities.chat.name_format: &2VIP &0&1>> &l{name}&r &1&0>>&r
command.ftbutilities.feed: true
ftbutilities.back.infinite

[vip+]
power: 30
parent: vip
ftbutilities.claims.max_chunks: 50
ftbutilities.chunkloader.max_chunks: 30
ftbutilities.chat.name_format: &5VIP+ &0&1>> &l{name}&r &1&0>>&r
command.ftbutilities.feed: true
command.ftbutilities.heal: true
ftbutilities.back.infinite

[admin]
power: 100
parent: vip+
default_op_rank: true
command: true
ftbutilities.claims.block.edit.gravestone.gravestone: true
ftbutilities.chat.name_format: &4Admin &1>> &f{name}&r &0>>&r
