### ISSUE TITLE
rainbow hud

### ISSUE THREAD

**Issue by Saturnion83** [FTBTeam/FTB-Utilities#1147]
so i don't know how but every hub of FTB utilities became rainbow, i think is something to do with developer mode or something (debug mode is off), i'm currently playing on skybees 
![Base Profile Screenshot 2021 02 27 - 19 46 28 01](https://user-images.githubusercontent.com/54741879/109397050-03dd6280-7935-11eb-9f48-3c8a5f670955.png)

**Comment by LatvianModder** [comment]
Press B to disable that. its a debug thing

**Comment by Saturnion83** [comment]
it didn't work i pressed b and also checked if debug mode was on in the ftbchunk setting and it's set on false

**Comment by Saturnion83** [comment]
> Press B to disable that. its a debug thing
it didn't work i pressed b and also checked if debug mode was on in the ftbchunk setting and it's set on false

**Comment by Saturnion83** [comment]
i fixed it by restarting the modpack, i dunno the cause
