### ISSUE TITLE
Dynmap support for 1.16.5 Forge

### ISSUE THREAD

**Issue by DNAmaster10** [FTBTeam/FTB-Utilities#1154]
I'm currently in the process of migrating from a Paper server to a Forge server. My server relies heavily on the use of Dynmap + Towny + Towny Dynmap in order to display borders on the Dynmap. I was wondering if there were any alternatives to these three plugins which support forge 1.16.5, and unfortunately I could only find one available for 1.12.2. I have nearly no programming knowledge when it comes to Java, however I believe that a mod which allows this would not be too complex to program. Area markers in Dynmap work by taking co-ordinates, and drawing a polygon shape using them. So to go about doing this, you'd only need to take the corners of claimed chunks, and feed the information into the Dynmap along with a few other parameters such as the colours. As I said, though, I have next to no programming knowledge with Java, so I'm probably underestimating largely how complex the mod would be. Thank you!

**Comment by MichaelHillcox** [comment]
This likely won't be added as we're not updating FTB Utils for 1.12+, you can find the map mod now as part of FTB Chunks.
