### ISSUE TITLE
Shop (+Money?)

### ISSUE THREAD

**Issue by LatvianModder** [FTBTeam/FTB-Utilities#126]
Add ingame shop where you can exchange items for other items, xp and possibly money. Money would  be disabled by default.

 Players can submit their own entries, but servers can setup infinite stock entries

**Comment by Dijkstra1** [comment]
Would there trade interface between players, so in real time, a player can see what i am offering, and offer something the think, I would be happy to try try for maybe even little trade chat so i can say i am not give a diamond, no matter how much dirt you offer me. player could send trade request for the player accept. Or would be more like this there say shop a player but something up for sell, in the shop, and say what they want for it, and other players, can go get that item with need to meat the other player, and the first player would told that they they items to get from the shop. I think both way would be useful on severs.  I was just wondering.
