### ISSUE TITLE
Additional Chunk Commands

### ISSUE THREAD

**Issue by TinkerWorX** [FTBTeam/FTB-Utilities#139]
Commands to control and reward the number of chunks claimable would be useful to map makers. Obviously, some consideration have be made if the max is set lower than the current. Possibly unclaim chunks in reverse order, although this would require tracking how they're claimed. Initially they could just be left as they are.
- /ftb team _teamname_ max_claimable_chunks set _count_
- /ftb team _teamname_ max_claimable_chunks add _count_
- /ftb team _teamname_ max_claimable_chunks sub _count_

The following command could make it so players can only claim chunks and not unclaim them.
- /ftb team _teamname_ chunk_claim_only _boolean_

The following command would force chunks to be connected, so it's only possible to claim a single area of chunks. Obviously wouldn't have any effect if no chunks have been claimed yet.
- /ftb team _teamname_ connected_claim_only _boolean_

It might be interesting to have the commands on a per player basis, and then just have it affect the players current team.

**Comment by LatvianModder** [comment]
I like the connected_claim_only, that I can add in team settings, but all other configs are actually still per-player. Chunks look like they are claimed by team, but actually limits are still per player. It will be easy to manage once I add ranks (soon™)

**Comment by LatvianModder** [comment]
Ranks added, this can be closed
