### ISSUE TITLE
Feature request: Daily perma backup

### ISSUE THREAD

**Issue by Nicba1010** [FTBTeam/FTB-Utilities#166]
So I want to constantly backup my game of course. I got it set to hourly backups and to keep 48 of them. I have the disk space. But what I'd like to see is the option to keep every n-th backup. Would that be possible? Thank you :) Btw what is the max compression level?

**Comment by LatvianModder** [comment]
max compresssion level is 9, iirc. Hm.. every n-th.. Rather than keeping, I would move that backup to a new folder instead. IF I can manage to figure out how to do it

**Comment by Nicba1010** [comment]
Thant'd be great, if I figure it out can I submit a pull request?

**Comment by LatvianModder** [comment]
Yeah
