### ISSUE TITLE
Chat Mute button

### ISSUE THREAD

**Issue by LatvianModder** [FTBTeam/FTB-Utilities#36]
Would have 3 modes - Normal, Muted, Semi-Muted
Normal - All chat is displayed
Semi-Muted - Only shows messages that contain your username or configurable keywords, e.g.
"Hey, LatvianModder!" would display but "Hello, how's it goin'?" wouldn't
Muted - All messages from players are hidden

**Comment by Dijkstra1** [comment]
Could you also set things such as semi mute I do not want hear anything for a certain player even if they use my name and also hear everything from an certain play even if they do not use my name, what I am suggesting is each player would have there own mute level and then global one for all player with out a mute setting maybe in the friend GUI you could have speaker button by all player which would toggle there mute level.

**Comment by LatvianModder** [comment]
That would be very complicated. Also, learn to use commas.

**Comment by Dijkstra1** [comment]
Complicated is ok, that the sort of things a like only one type of problem I like witch is impossible, so I am thinking this would probably need to stored client side. 
P.S.
I am sorry if my grammar is getting to you, but I do have mild dyslexia, which something can make written English hard to read, I tend to focus on spelling and getting words in the right order.

**Comment by LatvianModder** [comment]
Sorry :p I think I will make this function somewhat in groups, of people you only want to hear messages from or people you don't want to hear anything from at all
