### ISSUE TITLE
Dynmap support

### ISSUE THREAD

**Issue by gdude2002** [FTBTeam/FTB-Utilities#387]
**Curse**: https://minecraft.curseforge.com/projects/dynmapforge
**GitHub Wiki**: https://github.com/webbukkit/dynmap/wiki

Dynmap is a dynamically-generated Google Maps-style map that can be viewed from within a web browser. For example, [here's ours](https://forge.dynmap.gserv.me/?worldname=world&mapname=flat&zoom=6&x=-1092&y=64&z=301).

It would be nice if FTBUtilities could show a layer containing team-claimed chunks. As an example, here's a dead-simple knock-up of that.

![](http://i.imgur.com/QMClw6b.png)

(Not necessarily to scale but you get the idea)

**Comment by thetakodev** [comment]
Found this while looking for interesting mods. I think you can look at the source and implement this feature!
https://minecraft.curseforge.com/projects/warsftbdynmap
