### ISSUE TITLE
Claimed Chunk Visitor's Log

### ISSUE THREAD

**Issue by Noobsloth** [FTBTeam/FTB-Utilities#418]
I've been having issues with FTB Util's protections being bypassed. I know it's very hard to get everything every mod is doing, but one way to resolve the issue all together is to have a visitor's log.

This is aimed at small servers or servers where staff can access the log within ~6 hrs from the incident occurring. The add-on to FTB Utilities would log all players who visit a claimed area and several chunks around that area.  Then log that players name to the team's visitor's log with a time and location. Players would be able to access their own visitors logs and admin staff would need to as well. 

You can expand this visitors log to notify a player if another player has set a teleport in or near their claim. 

You can also expand to show the movement of the visitor within the claim chunks, so if there's grief and multiple people have visted you know which player has been to that area. 

This is something that would greatly improve FTB Utilities because it would add another layer of protection built in. Block loggers dont necessarily work very well due to the fact that they require a certain server configuration and sometimes don't do their job properly. 

I hope you take this suggestion into consideration,
Noobsloth

**Comment by monkeybug34** [comment]
Damn, I came to write exactly this post. you beat me to it!
