### ISSUE TITLE
Backup only if players are logged in

### ISSUE THREAD

**Issue by Ricket** [FTBTeam/FTB-Utilities#439]
Aromabackup has a setting to only do a backup if players have been logged in within the last backup duration. It looks like FTBU just backs up every time.

This is an RFE to please add a setting that a backup will only be taken if a player was logged in during the last backup duration. (including if a player logged in and back out within the timeframe)

**Comment by LatvianModder** [comment]
It used to do that, but I removed that feature for some reason. I think it was so I can port faster to 1.10 or something

**Comment by sandalle** [comment]
Looks to be related to https://github.com/LatvianModder/FTBUtilities/issues/262 .

**Comment by Ricket** [comment]
Hey, can you take another look at this? Seems like a really essential feature that is being overlooked.

**Comment by LatvianModder** [comment]
Maybe as default off - who knows what can loaded chunks without players do on their own. It makes more sense to always backup
