### ISSUE TITLE
Disable Suffocation Damage

### ISSUE THREAD

**Issue by dannydjdk** [FTBTeam/FTB-Utilities#484]
A feature that gives a configuration option to disabled suffocation damage. It's a common occurrence on many servers where teleportation glitches cause suffocation deaths. Suffocation kills a player in about 5 seconds regardless of armor and is nearly impossible to stop once it starts, and it rarely happens for legitimate gameplay reasons. This would be a very useful server utility feature.

**Comment by repairmant** [comment]
Then what ever mod is doing the teleporting should fix that bug on there end.

**Comment by dannydjdk** [comment]
@repairmant that "bug" is in Minecraft, not any specific mod. Teleportation with FTB Utilities is subject to this bug as well.
In any case, there's a mod called Login Shield (https://minecraft.curseforge.com/projects/login-shield) that fixes most of these cases, but I still think it would be a good feature to have in FTB Utilities.

**Comment by LatvianModder** [comment]
Sometimes I need remineder for small things like this
