### ISSUE TITLE
[API] Map Use

### ISSUE THREAD

**Issue by Mohron** [FTBTeam/FTB-Utilities#492]
From what I can tell this isn't currently possible but would you consider adding events and other necessary interfaces to your API to allow other mods to listen to interactions with your map and add information to the screen?

**Comment by LatvianModder** [comment]
I think it is possible currently, but anything specific you want me to add? I was gonna redesign the gui anyway

**Comment by Mohron** [comment]
With the current GUI design, there are 2 places I think it would be valuable to be able to add additional info, the hover tooltip, and the bottom left.

As far as the map, I was having a hard time figuring out how I would be able to act upon a user interacting with the map besides your built-in interactions (in ChunkModifiedEven: claim/unclaim/load/unload).
![image](https://user-images.githubusercontent.com/3623122/28548562-326f85c6-709a-11e7-803d-dc9c64f11674.png)
