### ISSUE TITLE
Physical way to show teams

### ISSUE THREAD

**Issue by ZombieHDGaming** [FTBTeam/FTB-Utilities#499]
Hey there, I was wondering if it was possible to add a way to show everyone your team or what not. I was thinking maybe a modified tablist to either add a way to show your team's color (if there is only as many teams as there are colors), or maybe adding an area under the player name to show your currently enrolled team's name or something......idk, just an idea for you. Like what you've done so far with the mod!

Cheers,
Zombie

**Comment by OldDogy** [comment]
Maybe adding something like 4 letter tag for teams ? And having that in front of people names ?

**Comment by thetakodev** [comment]
Ok, this would be really awesome
