### ISSUE TITLE
Admin team edition with commands

### ISSUE THREAD

**Issue by Autopoietico** [FTBTeam/FTB-Utilities#593]
I see various suggestion of adding a Admin GUI for editing teams without the use of the files from the ftb_lib folder, but can be possible adding this before only with commands?
This can made that admins can create automated tasks for the edition of teams, this can be added using the execute command in this way:
/execute nickplayer ~ ~ ~ /team set_status nickplayertwo ally
Or without the execute in this way:
/team nickplayer set_status nickplayertwo ally
This command can be used in the console panel and can be a first way to edit teams without using the files of the world in ftb_lib

**Comment by Column01** [comment]
Any update on this? Would be VERY useful for server administration.
