### ISSUE TITLE
Button conflict with NEI 1.12

### ISSUE THREAD

**Issue by jabari-austin** [FTBTeam/FTB-Utilities#608]
When you get a potion effect the sidebar buttons move to the top left of inventory and if you have a mod that adds buttons there (NEI) it gets in the way.

**Comment by LatvianModder** [comment]
I wonder if I can add NEI integration, so that those buttons are added there...

**Comment by jusitnboggs** [comment]
Yes Plz!

**Comment by Reignofmagic** [comment]
This still appears to be happening as of version
FTBUtilities-5.4.0.124

Bumping as a reminder.
