### ISSUE TITLE
Need more specific permissions (perms partially not working)

### ISSUE THREAD

**Issue by Simonmicro** [FTBTeam/FTB-Utilities#673]
Hi,
whats about a more specific permissions for the really basics (move, break, build) - without installing the Forgeessentials mod (which is currently not available for 1.12.2)? Or did I miss something? Or whats about a rank without any parent (or a parent) which doesn't include any permissions?
Thanks,
Simonmicro

**Comment by LatvianModder** [comment]
There are permissions for editing blocks (place+break) and interacting with blocks, but not for movement. There can't be a rank without a parent, if none is specified, `builtin_player` will be used

**Comment by Simonmicro** [comment]
@LatvianModder 
Thanks for your fast response, but I wasn't able to find that permissions (Block editing). I've looked at some sites ("https://gist.github.com/LatvianModder/54ccaee3af7a55d23831eac20f248a3f") but I cant find a clear list of all permissions for the default builtin_player rank (And I only found permissions for the claims ["ftbu.claims.block.edit.*"] - but I need the permissions for the global envroiment). Can you add to the wiki or write me here a link / list for the really basic permissions that also exist without ForgeEssentials? Or is there a ingame-command to create a list with all that permissions (Maybe you could add it)?

Thanks,
Simonmicro

**Comment by Simonmicro** [comment]
Or here an other example:

`{
	"default_ranks": {
		"player": "guest",
		"op": "admin"
	},
	"ranks": {
		"guest": {
			"parent": "builtin_player",
			"syntax": "<&7&oGast - $name&r> ",
			"permissions": [
                "-*"            
            ],
			"config": {}
		},
		"member": {
			"parent": "builtin_player",
			"syntax": "<&4Neutrales Mitglied&r> ",
			"permissions": [],
			"config": {}
		},
		"builder": {
			"parent": "builtin_player",
			"syntax": "<&6Bauteam - $name&r> ",
			"permissions": [
				"+worldedit.*"
			],
			"config": {}
		},
		"admin": {
			"parent": "builtin_op",
			"syntax": "<&9ADMIN - $name&r> ",
			"permissions": [],
			"config": {}
		}
	}
}`

The guest can still edit the world and the builder cant use worldedit. Looking at my config above, this shouldn't possible. I'm using "FTBUtilities-5.0.0.11.jar" and the permissions are not working for me.
See you,
Simonmicro

**Comment by LatvianModder** [comment]
Ah, I see, global permissions. Yeah, those aren't in, as noone has requested them before

**Comment by Simonmicro** [comment]
Okay ;) - Then here my official request: Please add global permissions for the players.
Also see my message above: Why is worldedit not working? The player 'builder' cant use worldedit commands - only if he is an OP. By the way: Thanks for your awesome mod - no one else is with updates so fast like you and your mod has got the biggest set of features (more than the old Server-TOOLs).
Thanks,
Simonmicro

**Comment by LatvianModder** [comment]
P.S. Use \`\`\` instead of \` for multiline code

**Comment by LatvianModder** [comment]
World edit may be using custom permissions? If it's `/worldedit` command, then use `+command.worldedit` permission

**Comment by Simonmicro** [comment]
Hi,
okay, thanks for your response. Official worldedit is using the bukkit and hMod permissions system (-> http://wiki.sk89q.com/wiki/WorldEdit/Permissions). At the moment there is no permission integration in other mods. Sorry for my ignorance. Maybe this could be added too - maybe you can cooperate with the team of worldedit to make a integration like in bukkit possible.
Thanks for all,
Simonmicro
