### ISSUE TITLE
Custom Sidebar buttons/commands

### ISSUE THREAD

**Issue by mrdeadlocked** [FTBTeam/FTB-Utilities#751]
The option to be able to added/create custom sidebar buttons that tie to commands would be great. An example could be to have a button for /home.

**Comment by LatvianModder** [comment]
But you can.. sidebar buttons are added from json on client side, look at how FTBU does it - https://github.com/LatvianModder/FTBUtilities/blob/master/src/main/resources/assets/ftbutilities/sidebar_buttons.json

**Comment by mrdeadlocked** [comment]
Awesome! Sorry about this then. :-)

**Comment by mrdeadlocked** [comment]
AH alright. I did get it to work. :-) How would I go about changing what the mouseover text is on the commands? Could this be an enhancement to bring this functionality to a more user-friendly method?

![image](https://user-images.githubusercontent.com/461352/40789081-90df351a-64bf-11e8-954c-48106f8c72d6.png)

**Comment by LatvianModder** [comment]
You add that key in your `en_us.lang` file, can't change it from json

**Comment by mrdeadlocked** [comment]
This is such a great feature but could be much more user-friendly. I'm sure more people would use this could be done through the settings or a config instead of directly editing the JAR. I updated FTButilies. I forgot to pack the sidebar_buttons.json on the new jar and lost my buttons. Would you be willing to possible add this to a long-term possible feature list?

**Comment by LatvianModder** [comment]
Sure, I always had an idea for custom buttons, I just never did it

**Comment by darthvader45** [comment]
Too bad I couldn't add a button with a function similar to NEI's magnet mode.

**Comment by darthvader45** [comment]
Maybe adding buttons with custom functions could be possible?  I'd like to make a magnet button, but it doesn't seem to be possible.

**Comment by balthild** [comment]
Is this possible for FTBU 1.0 for MC 1.7.10? There's no `sidebar_buttons.json` in the jar.

**Comment by LatvianModder** [comment]
No, all 1.7 versions are completely dead lol
