### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by generrosity** [FTBTeam/FTB-Utilities#788]
Apologies if this is a trivial thing, I couldn't find it on Google YouTube or the wikis.

Is it possible to add additional leaderboards, such as counting for each person the number of blocks broken and placed? And the number of different mods interacted with (presumably placed at least one block)?

Thanks!

**Comment by LatvianModder** [comment]
You can't add those yourself, but you can request me to add those :P

**Comment by generrosity** [comment]
😜 I think they would be a valued addition! Our people are builders primarily - so building is more impressive! And with the kitchen sink mods would be cool to see how varied people have gotten in to

Thanks for the consideration at least 😜

**Comment by generrosity** [comment]
Additional leaderboard ideas - 

- Most Server Friendly (number of chunk loaded forced chunks via FTBU or Weirding Gadget etc, in increasing order - as a mini server admin this would actually be quite a handy stat to know ... coz asking for 'who costs me the most TPS' isn't happening soon!)
- Land Grabbing Tycoon (number of FTBU claimed chunks in decending order)
- Top logins (rather than top total time - people who pop in for many half hour sessions, rather than huge sessions)

**Comment by Nedok** [comment]
I have to agree that some more stats could be fun.
But I believe that there is already a lot of stats in MC that could be presented.
Damage Taken, Player Kills, Times Slept in a Bed, Distance by [a lot of travel method]
Total blocks mined, total item used, total item placed could also be interesting but might be slightly harder to implement.
