### ISSUE TITLE
Add something to the tab menu to see if a player is AFK

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Utilities#834]
Maybe make their player name darker or something, I don't know if it's actually possible to change the tab menu. If not, maybe a command or something in the FTBU menus?

**Comment by LatvianModder** [comment]
I think its possible

**Comment by merphle** [comment]
I was just thinking about wanting this behavior today. Is this closed/wontdo, or is it something we can look forward to seeing?

**Comment by LatvianModder** [comment]
This has been implemented already

**Comment by merphle** [comment]
Thank you! Do you happen to know which build version it's part of? I don't think I see any AFK-related display on the user list. I'm running FTB Sky Adventures 1.4.0, which uses FTBUtilities 5.3.0.69.
