### ISSUE TITLE
Tp to nearest unclaimed chunks

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [FTBTeam/FTB-Utilities#868]
With my request of being able to have each person claim blocks on a team I also suspected there might be an issue with scattered claims. It would be nice to have a to command that tp a player to the nearest unclaimed 10 x 10 chunk area center. (Configurable may be nice) It would just need to be a by squared calculation such as 2x2 3x3 4x4 etc. Just a general squared radius.

**Comment by thetakodev** [comment]
Maybe you can get a random position from spawn (in a small range) and if there is no claim, teleport the player. If there is, increase range by a bit and save the increased range, for the next time someone uses the command.

**Comment by LatvianModder** [comment]
There is /rtp
