### ISSUE TITLE
/god command

### ISSUE THREAD

**Issue by TacticalUniverse** [FTBTeam/FTB-Utilities#878]
I had people asking on one of our servers if maybe you guys can add /god to FTBU like Essentials has

**Comment by LatvianModder** [comment]
What does it do?

**Comment by TacticalUniverse** [comment]
Set specified player's invulnerability status to where players cant be attacked or targeted by anything

**Comment by thetakodev** [comment]
I would like to see this, and more features from Essentials in the mod.
