### ISSUE TITLE
Is the tpaccept command working? 

### ISSUE THREAD

**Issue by majinboyo** [FTBTeam/FTB-Utilities#884]
The tpa command works but I can't get the tpaccept command to work. I typed command.ftbutilities.tpaccept: true in the ranks.txt file, but I still can't use the tpaccept command. Did I type it wrong or is it bug?

**Comment by LatvianModder** [comment]
You may have to enter the name of player too. You can also click on the button that shows up in chat. If this /tpa is from another plugin, I can't fix that

**Comment by majinboyo** [comment]
I tried /tpaccept [player's username] and the chat says ftbutilities.lang.tpa.requested_accepted but nothing happened. The player does not get teleported to me or if I send a tpa request, I don't get teleported to the player if accepted. I only have ftbutilities and ftblib.
