### ISSUE TITLE
Chunk Loading Messes With Fluid Updates

### ISSUE THREAD

**Issue by EmosewaPixel** [FTBTeam/FTB-Utilities#896]
So, when you have a pump that collects source blocks in a chunk loaded area, no matter how big the pool of water is, the pump collects all the blocks, probably due to new source blocks not being created. This seems to be related to FTB Utilities chunk loading as it does not happen when players or chunkloading blocks from certain mods are in said chunk. This has been tested by multiple times bu different groups of people on version 5.3.0.53, though, looking at your recent commits, I don't think it's been fixed.

**Comment by LatvianModder** [comment]
You must allow fake players in your chunks then
