### ISSUE TITLE
Add mob spawning flag for teams claim

### ISSUE THREAD

**Issue by egori477** [FTBTeam/FTB-Utilities#898]
Mb I don't see it (when, please, say how can I do it?), but I want flags for off/on mob spawning in claimed areas.

First, for angry mobs (monsters).
Second, mb for animals (but monsters - main!).

**Comment by thetakodev** [comment]
It will be awesome if it is going to be a feature configurable in the permissions. (So only specific people can enjoy the luxery of no mobs on their claims)

**Comment by nephatrine** [comment]
I also think this would be a great feature to add.
