### ISSUE TITLE
Trash Can Can't Be Opened When Chat Is Set To Hidden

### ISSUE THREAD

**Issue by EmosewaPixel** [FTBTeam/FTB-Utilities#899]
When Chat is set to Hidden in the Chat Settings, a Trash Can can't be opened (i.e. it never stops loading), only the Trash Can...
![image](https://user-images.githubusercontent.com/25333164/49668329-09051d00-fa5e-11e8-9f40-857faa17907e.png)
![image](https://user-images.githubusercontent.com/25333164/49668337-0e626780-fa5e-11e8-970b-00f538a9e2fd.png)

**Comment by LatvianModder** [comment]
Huh. Well, set that to Commands Only then

**Comment by thetakodev** [comment]
Have you tested anything else? I think there might be similar issues with other buttons.
