### ISSUE TITLE
Name Format

### ISSUE THREAD

**Issue by vertex101** [FTBTeam/FTB-Utilities#912]
+ See if the issue isn't already reported / suggestion been made by looking up some keywords.
+ If it is, don't comment that you have the same issue, just press :+1:
+ Bugs and Suggestions will only be accepted and implemented/fixed for latest minecraft version, unless it's compatible with older one.
+ Do not add versions or "[Bug]" or "[Suggestion]" in issue title, I will tag them.
I am using FTBUtilities-5.3.0.68 and i am trying to get the name format of ranks

this is the code i am trying to use

`&c[Owner]&0&l{name}`

i have tried doing it with and without the `<>`

when i run the command in-game it just tells me `Nothing changed!`

here is a little video of me trying to run the command in-game
https://vertex101.tv/img/2x36t40c60r8.mp4

and also here is my ranks.txt
https://gist.github.com/vertex101/f7469ef1b8e232356b2f0cfff62a1578

**Comment by LatvianModder** [comment]
Your site is down. Make sure you update to latest, some bugs were fixed and read this https://minecraft.curseforge.com/projects/ftb-utilities/pages/ranks/config
