### ISSUE TITLE
Trying to backup to an absolute file path.

### ISSUE THREAD

**Issue by Jager67** [FTBTeam/FTB-Utilities#913]
Version: FTBUtilities-5.3.0.68
LIB Version: FTBLib-5.4.0.73
Running Windows as the OS.

What I've tried for file path so far.
    # Absolute path to backups folder.
    S:folder= Z:\Pixelmon
    S:folder= \\Z:\Pixelmon
    S:folder= \Z:\Pixelmon
    S:folder= :Z:\Pixelmon
    S:folder= Z:\Pixelmon\
    S:folder= Z:/Pixelmon

When trying to add a file path to run backups to I get an error stating...
([File IO Thread/INFO] [STDERR]: [com.feed_the_beast.ftblib.lib.util.FileUtils:newFile:49]: java.io.IOException: The filename, directory name, or volume label syntax is incorrect)

[backuplog.txt](https://github.com/LatvianModder/FTBUtilities/files/2723562/backuplog.txt)

If you need any other information please let me know.

**Comment by LatvianModder** [comment]
I think you have space between `=` and path, there shouldn't be one
