### ISSUE TITLE
Need ability to set permissions per claimed chunk and not just the entire claim.

### ISSUE THREAD

**Issue by kreezxil** [FTBTeam/FTB-Utilities#914]
This would come in handy for players that wish to sell things via mods that allow vending machines or contraptions that they have created. That way they can specify a set of chunks as interaction prohibition none so that all players can interact there and keep the rest of their claims as default no interaction.

**Comment by LatvianModder** [comment]
https://github.com/FTBTeam/FTB-Utilities-Chunks/issues/1
