### ISSUE TITLE
FTBUtilties & Forge Essentials comparability

### ISSUE THREAD

**Issue by MacWhinny** [FTBTeam/FTB-Utilities#916]
Hi there. I've been talking to the dev for Forge Essentials about claims as in his mod you cant setup per rank plots, so we turned off the ranks for FTBU to try give his mod power over the per rank claim amounts but he had this to say.

ftbu forgets to insert this node when not the default perm handler
it should be like this: /p user Zethalion value ftbutilities.claims.[tab] and max_claim has to show up
it doesn't thus is not registred
and if it is not registered, it won't be used
ftbu needs to fix this
I find this odd as LatvianModder as author of ftbu teaned up with FE to have this api implemented

The ATM3 Remix modpack is updating soon and it would be awesome if a fix could be done for this as there is an issue with the TPA command saying players do not have perms when i as op do. nothing we have tried fixed this so the only thing left is the turn off ranks through FTBU and give per rank claims through FE

**Comment by LatvianModder** [comment]
The API doesn't support numbers. which max claimable chunks and loadable chunks are. The API in Forge only works for true/false values. If you turn off all FTBU ranks, it will just use default values and won't mess with permissions

**Comment by MacWhinny** [comment]
So there is no way to set your own mods claim/chunkloading amount with other permission managers? 

I don't want to use FE's plots as there no way of giving 10 to the default rank 20 to the next rank 30 to the next rank and so on. but if i keep using the ranks from FTBU for what ever reason there is a conflict between FTBU and FE tpa. Me as OP can do it, but everyone else it says they do not have perms. Even the Dev of FE came onto my server and couldn't get it to work and said that it would if i turn FTBU ranks to false. There lays my dilemma. If i turn off ranks i lose per rank claims, but gain tpa. if i stick with FTBU claims i keep rank claims but no one can do tpa. Can something not be sorted out as both your mods are collaborating with each other to make them work and the ATM3 dev team is looking into adding FE into their mod-pack.

**Comment by LatvianModder** [comment]
You can disable any ftbu command in config file, so that it wouldn't conflict

**Comment by spacebuilder2020** [comment]
If you set the ftbu tpa to false, that probably means that the FE tpa is active.  Make sure to compare /fetpa to /tpa

**Comment by spacebuilder2020** [comment]
I have added a compatibility layer to Forge Essentials to support FTBU permissions.  max_claims should now work.

**Comment by MacWhinny** [comment]
Ok so, when i have tpa set to false with FTBU and get a player to run tpa or fetpa it was telling players they do not have perms. which is strange when as op i can do them. Even Zethalion couldn't get it to work and told me that i needed to disable ftbu ranks. But with Plots not having a way to setup per rank claim amounts i can't do that. 

Can you please explain what you mean by I have added a compatibility layer to Forge Essentials to support FTBU permissions. max_claims should now work.
also the update you make a few hrs ago looks to be for 1.10.2, my server runs 1.12.2

**Comment by spacebuilder2020** [comment]
The update is on Jenkins.  Curse builds don't get updated until they have been tested.

**Comment by MacWhinny** [comment]
right gotcha, do you have the link for that. lso could you please explain what has been changed/enabled so i can fully understand.

**Comment by spacebuilder2020** [comment]
The link is on Forge Essentials [Readme](https://github.com/ForgeEssentials/ForgeEssentials#reporting-bugs).

As for what changed, I needed to implement the IRankConfigHandler class to support FTBU rank based configs.  Remember to leave ranks disabled.

**Comment by spacebuilder2020** [comment]
It has been tested with forge 2784, ftblib 5.4.1.75, and ftbu 5.3.0.72

**Comment by MacWhinny** [comment]
so for instance, if i setup ranks and have the claims setup with it, FE will pick those claims up and run them as if the FTBU ranks were set to true?

**Comment by spacebuilder2020** [comment]
No, you need to define the permissions in FE.  It will not read any FTBU ranks.  
For example `/p user Spacebuilder2020 value ftbutilities.claims.max_chunks 9` will set my user's max_chunk value to 9.

**Comment by spacebuilder2020** [comment]
One thing to note, is for some reason, you will need to restart the server after editing max_chunks.  I have not yet determined why.

**Comment by MacWhinny** [comment]
awesome, really hope this works. as this two perm managers is messing with things

Ok that's not an issue, used to it with FTBU needing the server off to make any changes. Else they don't stick

**Comment by spacebuilder2020** [comment]
As long as ranks are disabled in FTBU, it should work since FTBU ranks uses the same permission handler that FE uses.

Currently, FE is unable to defer to Ranks, so things might break if it is enabled in any version of FE.

**Comment by MacWhinny** [comment]
![capture](https://user-images.githubusercontent.com/45312580/51082417-58dea000-16fe-11e9-8eb3-671b9a6a131c.PNG)

So i did that command and it shows as going through, FTBU ranks is set to false, did a restart and nothing changed from what it was before

**Comment by spacebuilder2020** [comment]
At this point, this is not an FTBU bug.
Please return to the issue on FE.
https://github.com/ForgeEssentials/ForgeEssentials/issues/2387

**Comment by darkcamo12** [comment]
I know this issue is closed but I'm wondering if this could be related to FTBUtilities 

https://github.com/ForgeEssentials/ForgeEssentials/issues/2413

**Comment by spacebuilder2020** [comment]
That is a separate issue.  This issue was strictly for inter mod compatability between FE and FTBU.  That was implemented.  The issue that is occurring has to do with ender io interfering with FE and FTBU.
