### ISSUE TITLE
Crash On Server Tick (1.12.2)

### ISSUE THREAD

**Issue by nephatrine** [FTBTeam/FTB-Utilities#920]
* FTBLib-5.4.1.75.jar
* FTBUtilities-5.3.0.72

Updated to the latest versions of FTBLib and FTLUtilities and now crash when loading a world.

```
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from FTB Utilities (ftbutilities)
Caused by: java.lang.NoSuchMethodError: net.minecraftforge.fml.common.ObfuscationReflectionHelper.getPrivateValue(Ljava/lang/Class;Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;
	at com.feed_the_beast.ftblib.lib.util.CommonUtils.getModContainerForClass(CommonUtils.java:32)
	at com.feed_the_beast.ftbutilities.FTBUtilities.onServerStarted(FTBUtilities.java:112)
```

**Comment by LotuxPunk** [comment]
Same https://pastebin.com/fDn303wE

**Comment by nephatrine** [comment]
Looks like this no longer works on the recommended forge version. I wasn't sure what version it needs but it looks like it's build against 1.12.2-14.23.5.2784 so I switched to that version and no longer have this issue. Mod needs either minimum version incremented or modified to work with recommended version.

**Comment by ifficles** [comment]
I have the same above issue with the latest update.  I updated to the 2784 version of forge, and still received the same error.  I am downgrading to the December release of FTB utils, as that will allow my game to load.  Crash log is here - https://paste.ee/p/e7qYs

**Comment by DarkRisenGaming** [comment]
Having the same issues, using Recommended Versions of Forge, and Also went back many Versions
Of the FTBUtilities and still having problems.

**Comment by LatvianModder** [comment]
I hadnt updated required forge version in FTBLib, I did that now. I don't usually use recommended versions of forge because mostly they are old
