### ISSUE TITLE
Server Restart Issues

### ISSUE THREAD

**Issue by MordridtheBlack** [FTBTeam/FTB-Utilities#923]
+ See if the issue isn't already reported / suggestion been made by looking up some keywords.
+ If it is, don't comment that you have the same issue, just press :+1:
+ Bugs and Suggestions will only be accepted and implemented/fixed for latest minecraft version, unless it's compatible with older one.
+ Do not add versions or "[Bug]" or "[Suggestion]" in issue title, I will tag them.

Modpack: World of Dragons
Minecraft Version: 1.12.2
Forge Version: 14.23.5.2807
Modpack Version: 14.12.144
Server Host: Creeper Host (Minecraft recommended)

Problem in question; The server, instead of restarting, shuts down. Owner of the server has to take the time to manually restart the server.

Note: Other modpacks, with this mod in it...run by the same person, have restarted just fine, with no issues.

I am making a new post because the last post even coming close to this one was in 2017, and I'm not sure if the same fix still applies, or if something new has arisen.

**Comment by LatvianModder** [comment]
There is no server restart option, only shutdown. Server owner must make a script on his side to auto-restart server after it has been shut down
