### ISSUE TITLE
Patch Notes Missing  Important Info

### ISSUE THREAD

**Issue by EnragedN3wb** [FTBTeam/FTB-Utilities#926]
Please for the love of god include extremely important info in the patch notes...

"Updated minimum required forge version - LatvianModder"

Tells me absolutely nothing about WHAT forge version is required. Just wasted 20 minutes updating my server to the latest version of FTBLib & FTBUtilities only to find out I now have to undo it because I'm using 14.23.5.2768 & not 14.23.5.2784.

Edit: Apparently FTBLib & FTBUtilities share an issues page.

**Comment by LatvianModder** [comment]
Done. You can always just update forge too...

**Comment by LatvianModder** [comment]
There almost never is a reason not to update. If something bad happens, forge gets patched quickly
