### ISSUE TITLE
Can't locate my ranks.json file

### ISSUE THREAD

**Issue by memester07** [FTBTeam/FTB-Utilities#929]
Me and a couple of my friends are trying to use ftbutilities to claim vast swaths of land (Its a 8000x8000 map of Europe), however due to the cap we cannot claim as much as we would like too. I have googled the problem but everyone else appears to be in a different version of ftbutilities, as I cannot find the ranks.jason file in the local folder. I have another modpack (This is all through Curse) that had the older version that worked just fine on 1.10.2. Any suggestions?

FTButilities version 5.3.0.68
FTBLib version 5.4.0.73

It might help you in that we have adding stuff to another modpack for our own little server (Minecolonies Getting Started), which I then downloaded FTButilities and FTBLib and added them independently.

**Comment by memester07** [comment]
Minecraft Forge 14.23.5.2807

**Comment by LatvianModder** [comment]
It's gone, there's ranks.txt file now, see https://minecraft.curseforge.com/projects/ftb-utilities/pages/ranks/config
