### ISSUE TITLE
FTBUtilities 5.3.0.71crashing spongeforge on startup

### ISSUE THREAD

**Issue by AkiSenpai96** [FTBTeam/FTB-Utilities#933]
Hey,

I installed FTBLib and FTBUtilities and according to crash report it's crashing because of FTBUtilities

[crash-2019-02-01_01.06.59-server.txt](https://github.com/FTBTeam/FTB-Utilities/files/2819698/crash-2019-02-01_01.06.59-server.txt)

**Comment by LatvianModder** [comment]
Update Forge version

**Comment by AkiSenpai96** [comment]
Thing is that spongeforge only uses that forge. And it's the latest forge.
Might aswell wait when they update the spongeforge

Na(o) Sáb, 2 de fev de 2019, 00:09, Kristiāns Micītis <
notifications@github.com> escreveu:
