### ISSUE TITLE
FTBU claims + Trade o Mat

### ISSUE THREAD

**Issue by MacWhinny** [FTBTeam/FTB-Utilities#935]
Hi, i know you can set the interactions to none to let anyone interact in your FTBU claim, but this brings it's own issues with other people then being able to gain access to chects, I runa  server and i'm trying to set up a market world. I'm using the Trade o Mat as there is no shop mod out there that is server side only. 
The problem i'm having is that people cant use the Trade o Mat unless you allow interactions in your claim. But this opens up griefing. 
Is there a way you can add a feature so that certain blocks can be interacted with regardless of the settings you have set up for your claim. 

I'm running 1.12.2 with forge-1.12.2-14.23.5.2784 for the ATM3 Remix 1.0.1 mod-pack

**Comment by LatvianModder** [comment]
IC2 machines use one ID, there is no way to whitelist specific machine :/
