### ISSUE TITLE
Override Sidebar Buttons From Config

### ISSUE THREAD

**Issue by NillerMedDild** [FTBTeam/FTB-Utilities#940]
Hello o/

I would like to request the ability to override the toggling of sidebar buttons from the config file. 
Essentially I want to forcefully remove the gamemode/rain/day/night/heal buttons, because they remind me I can cheat :P it breaks immersion a bit.

**Comment by LatvianModder** [comment]
You can, inventory -> Client Settings -> Sidebar buttons

**Comment by NillerMedDild** [comment]
I'll rephrase, I would like a config option to forcefully disable some sidebar buttons, disallowing the client to reeabling them, without going into the config in the config folder. It's probably too much to ask for now that I think about it ^^'
