### ISSUE TITLE
help - setting team fake player status to none by default

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [FTBTeam/FTB-Utilities#943]
![2019-02-26 10_17_52-minecraft 1 12 2](https://user-images.githubusercontent.com/10351221/53428408-5daa9b00-39b0-11e9-8683-b16bee95624b.jpg)
![2019-02-26 10_18_03-minecraft 1 12 2](https://user-images.githubusercontent.com/10351221/53428415-600cf500-39b0-11e9-95c6-4bcc63d39352.jpg)

**Comment by P3rf3ctXZer0** [comment]
I can't seem to find a permission to set that.

**Comment by LatvianModder** [comment]
Because people complain some machines dont work by default. If you want to disable them, you can do that yourself for your team

**Comment by P3rf3ctXZer0** [comment]
Okay so what is the permissions I need to set so at least it is default for my server?

**Comment by LatvianModder** [comment]
There is no default setting for that
