### ISSUE TITLE
Home, tpa, permissions broken?

### ISSUE THREAD

**Issue by zCodeg** [FTBTeam/FTB-Utilities#948]
Modpack: Stoneblock 2 - 1.8.0
FTB-Utilities: 5.4.0.84
Error: Sender is not a player!

Unable to list other players homes with command /home list <player-name> anymore
Operators and players with ftbutilities.other_player.homes.list permission affected

Also can list my own homes, but cannot teleport to them by clicking the name.
Also.. while having permissions cannot teleport cross_dim
And the same with /tpa (/tp in same dimensions - working)

On command run:
![image](https://user-images.githubusercontent.com/5285811/53663117-890dde00-3c6d-11e9-985e-120641f13e5e.png)

Did anything change in permissions? Feels like broken :o

**Comment by P3rf3ctXZer0** [comment]
https://github.com/FTBTeam/FTB-Utilities/issues/948 These issues are the same.

**Comment by P3rf3ctXZer0** [comment]
Yeah they may have broken the player check watchdog. At any rate for now it appears tpa is broken.

**Comment by P3rf3ctXZer0** [comment]
Cause this is my rank table.

https://gist.github.com/P3rf3ctXZer0/e59ef914abfcf0995609124582bc6d8d

**Comment by P3rf3ctXZer0** [comment]
More issues that may be cause by ranks.

https://gist.githubusercontent.com/P3rf3ctXZer0/b5dbc184b988ebd9706f33754c6b4d00/raw/91ac85eea14993ad7e14500b54b1d032be8f9a6f/gistfile1.txt

**Comment by christo666** [comment]
Same problem here after updating Stoneblock2 to v. 1.8.0 BETA
