### ISSUE TITLE
since the update i get error occurred  while attempting to perform this command the command im trying to use is /tpa

### ISSUE THREAD

**Issue by phantom1151** [FTBTeam/FTB-Utilities#949]
+ See if the issue isn't already reported / suggestion been made by looking up some keywords.
+ If it is, don't comment that you have the same issue, just press :+1:
+ Bugs and Suggestions will only be accepted and implemented/fixed for latest minecraft version, unless it's compatible with older one.
+ Do not add versions or "[Bug]" or "[Suggestion]" in issue title, I will tag them.

**Comment by P3rf3ctXZer0** [comment]
Its caused by broken ranks. 2d3eb2575f2b5639bdfa8d88cb9d5e52 I have the same issue. I cannot even change the ranks and trying to check rank status breaks the game and causes a server crash.

**Comment by P3rf3ctXZer0** [comment]
https://github.com/FTBTeam/FTB-Utilities/issues/948
