### ISSUE TITLE
Sender is not a player!

### ISSUE THREAD

**Issue by NLBlacky** [FTBTeam/FTB-Utilities#951]
**Mod versions:** FTBUtilities-5.4.0.84.jar, tried with FTBUtilities-5.3.0.81.jar as well later on since that was the version in the client files, while the other one was in the server files.
**Other mod versions:** FTBLib-5.4.1.85.jar
**Modpack:** Ultimate Reloaded v1.2.1

**Issue:** We started a new server on the modpack Ultimate Reloaded which has FTBUtilities included.
We've been using FTBUtilities since the start of our first server 7 months ago so we're familiair with the mod.

When giving a rank I get the error "Sender is not a player!". See the exact log below:
**Error message in console:** [Console](https://pastebin.com/aJPA8kxx)
**Server log:** [Log](https://pastebin.com/0aY0Ppn9)

I tried to run the command in-game and via console, both giving the same error.
I've also cleared the local folder so a new one would be generated, that did sadly not fix it.

Since the issue was on both FTBUtilities versions (that are listed in the top of this post) I believe the issue is caused by something else which might also be causing the garbage-collecting leak. I however did not know how to track it correctly which is why I made this post.

**Comment by NLBlacky** [comment]
I see you closed the topic without any reaction to it. May I ask why?

**Comment by LatvianModder** [comment]
Because I fixed and updated it

**Comment by NLBlacky** [comment]
I'm glad to hear that. I however do not understand how it is also happening to FTBUtilities-5.3.0.81.jar which is a month old.

**Comment by LatvianModder** [comment]
It was an FTB Lib bug

**Comment by NLBlacky** [comment]
Alright, thank you for the clarification!
