### ISSUE TITLE
leaderboards incorrect play time and gui

### ISSUE THREAD

**Issue by frakier** [FTBTeam/FTB-Utilities#956]
First not sure either of these are a FTB problem or something I have done and looking for a little direction.

Second is the GUI, no back button so you have to esc and then go back into inventory to get to the leader boards. Which seems clumsy, have I broke it on my end?

Third my playtime is nowhere near actual play time or death count. Could I have reset or erased that data somehow on the client or server side? We are using serversync to sync the mods folder and the configs folder but as far as I can tell that should not interfere with how you store the data on the player.

Thanks.

**Comment by LatvianModder** [comment]
Data is directly read from your vanilla statistics. It should match whatever you see when you press the Stats button in escape menu
