### ISSUE TITLE
Crash when player join server or singe world

### ISSUE THREAD

**Issue by Leaveleaf** [FTBTeam/FTB-Utilities#957]
Crash when player join server or singe world, sorry my English is poor. https://paste.ubuntu.com/p/77zjYYqQCj/

use:
OpenJ9 
FTBLib-5.4.1.86.jar 
FTBUtilities-5.4.0.85.jar
sampler-1.80.jar

but old ftbu(FTBUtilities-5.3.0.82.jar) nothing

**Comment by LatvianModder** [comment]
Use Java 8

**Comment by Lartza** [comment]
@LatvianModder That is Java 8, my SMP server crashes on startup with the same error

**Comment by Lartza** [comment]
Client didn't have sampler, derp.

@Leaveleaf Update sampler to at least 1.81

**Comment by Leaveleaf** [comment]
yep, I updated it, it is normal now. 
you can paste the log
