### ISSUE TITLE
i modify the ranks.txt to delete command but not working

### ISSUE THREAD

**Issue by dablackM** [FTBTeam/FTB-Utilities#960]
[player is default_player_rank]
example.permission: true
example.other_permission: false
command.ftbutilities.spawn: false

but the players can still use spawn in my sever

**Comment by LatvianModder** [comment]
are those players OP?

**Comment by dablackM** [comment]
No, they aren’t, and I use the sponge for sever. Is that relevant?

**Comment by LatvianModder** [comment]
Oh.. well I can't help with Sponge as it completely breaks FTBU, sorry. Use either of two mods
