### ISSUE TITLE
New Leaderboard counter for Sneaks (twerks)

### ISSUE THREAD

**Issue by merphle** [FTBTeam/FTB-Utilities#969]
Similar to number of jumps, this is just number of sneaks. Probably more relevant for certain skyblock-style packs; might be amusing to see.

**Comment by Naxanria** [comment]
As this is not a vanilla stat, I doubt this will be implemented.
https://minecraft.gamepedia.com/Statistics

**Comment by LatvianModder** [comment]
Yes, I can only track vanilla stats. If its not, I have to track them myself and I don't want to really do that
