### ISSUE TITLE
FTbUtilities - Backup : Optional dependency

### ISSUE THREAD

**Issue by LotuxPunk** [FTBTeam/FTB-Utilities#972]
Hello !
Would it be possible to remove FTBUtilities: Backup of your libraries required? It's quite annoying to have to remove it every time in modpacks when you use something else to make your backups.
Thank you in advance for your understanding!

**Comment by LatvianModder** [comment]
My plan is to split more parts off into their own separate mods, and then the main project would be a bundle. Then I will remove that of course, but that might not be until late may, unfortunately you will have to deal with that until then
