### ISSUE TITLE
Automatically assign rank based on playtime?

### ISSUE THREAD

**Issue by katubug** [FTBTeam/FTB-Utilities#975]
Hi! I did some searching and couldn't find anything for "auto rank" or "autorank" or even "auto."

Basically, I'd like to set up a way to assign FTBUtils ranks to my players automatically, based on how many hours they have logged on the server. I've been trying to set it up via plugins, but I'm having a hell of a time getting it to play well with FTBUtils. Is there any way to do it natively, or any plan to add it?

Thanks for your time!

**Comment by LatvianModder** [comment]
There is plan, after I split the mod into more modules https://github.com/FTBTeam/FTB-Utilities-Ranks/issues/2
