### ISSUE TITLE
Sidebar not showing up in survival mode

### ISSUE THREAD

**Issue by slushieboy99** [FTBTeam/FTB-Utilities#979]
The top-left sidebar does not show up on my server when players are in survival mode. It only shows up when players are in creative mode strangely.

**Comment by LatvianModder** [comment]
Hm. Maybe NEI is installed or some other mod that messes with it

**Comment by slushieboy99** [comment]
NEI Is not installed, but I believe it to be a modpack issue. When opening the baubles menu, I am able to see the sidebar.

**Comment by LatvianModder** [comment]
Hm, something replaces default inventory most likely, I can't fix that
