### ISSUE TITLE
Chat text color

### ISSUE THREAD

**Issue by Jnorris8412** [FTBTeam/FTB-Utilities#980]
I don't see any documentation on what colors you can use for ftbutilities.chat.text.color. Is there a way you could include it within local/ftbutilities/ ?

**Comment by LatvianModder** [comment]
Im pretty sure all_permissions.html lists them. They are
`black, dark_blue, dark_green, dark_aqua, dark_red, dark_purple, gold, gray, dark_gray, blue, green, aqua, red, light_purple, yellow, white`
