### ISSUE TITLE
MOTD using /tellraw for URL to Discord

### ISSUE THREAD

**Issue by Vileartist** [FTBTeam/FTB-Utilities#983]
Hi there! I'm trying to figure out how to enable a URL hyperlink in the MOTD for my FTB Revelation server. I've looked through other Issues related to MOTD and many of them seem so close to giving me the answer but I'm missing something.. I don't understand how to enable the /tellraw command for the MOTD.

Using FTBUtilities-5.3.0.69 in FTB Revelation 2.7.0 

I enabled MOTD in the server ftbutilities.cfg with:
    # Enables message of the day.
    B:enable_motd=true

I've tried editing the MOTD line and have successfully allowed it to post standard text lines as such:

    # Message of the day. This will be displayed when player joins the server.
    S:motd <
        "Welcome to Vile Nation! Please check out our Discord for Server rules and discussion! https://discord.gg/Q8BMf8b"
        "My name is Vileartist! I'm the server owner and a Twitch Streamer! Come check out my channel! https://www.twitch.tv/vileartist"
     >

This works fine but of course the URL is not clickable. So through more research I discovered that you added support for URLs through /tellraw commands but I cannot for the life of me figure out how to incorporate them because any attempt to add a /tellraw to the S:motd < line causes it to simply not appear at all.

I have tried using minecraft.tools /tellraw editor to generate a command and the result still failed. This is what I have attempted:

    # Message of the day. This will be displayed when player joins the server.
    S:motd <
        /tellraw @a ["",{"text":"Welcome to","bold":true,"color":"dark_blue"},{"text":" "},{"text":"Vile Nation!","italic":true,"underlined":true,"color":"light_purple"},{"text":" Please check out our "},{"text":"Discord","color":"dark_aqua","clickEvent":{"action":"open_url","value":"https://discord.gg/Q8BMf8b"}},{"text":" for Server rules, information and discussion!"}]
     >

Please can you give me some insight on how I can do this correctly? I do not know what I am doing incorrectly.

**Comment by LatvianModder** [comment]
The tellraw syntax is correct, just remove the `/tellraw @a ` part, it only needs json
