### ISSUE TITLE
No text

### ISSUE THREAD

**Issue by SubMGRru** [FTBTeam/FTB-Utilities#985]
![изображение](https://user-images.githubusercontent.com/18516370/57123991-9f7b0780-6d8c-11e9-98c8-7c6e853c5b50.png)
Hello, yesterday I installed fbuttilites and ftblib. I do not see the text of the teams, but only their names, so absolutely with all the teams (/ tpa, / team join), the text is not visible. Other modes normally display text. In the photo below, this problem is captured. I use the latest version of forge and the latest version of ftblib and ftbuttilites. Help! I tried to reinstall the mods but it did not help.

**Comment by LatvianModder** [comment]
This happens when mod is not on client side, I can't fix this. You either add the mod on client or make server resource pack with language files from mod
